apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.imageTag}}
        imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
        name: {{ .Values.name }}
        ports:
        - name: {{ .Values.name }}
          containerPort: {{ .Values.imageConfig.port }}