apiVersion: v1
kind: Service
metadata:
  labels:
    name:  {{ .Values.name }}
  name:  {{ .Values.name }}
spec:
  ports:
    - protocol: "TCP"
      port: {{ .Values.port }}
      targetPort: {{ .Values.imageConfig.port }}
  selector:
    app:  {{ .Values.name }}